server:
  port: 8282

spring:
  application:
    name: get-guide
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://ec2-34-236-103-63.compute-1.amazonaws.com:5432/d9b4pr7113hdda
    username: qvmiimmumjtndv
    password: 17db20f9f7055fd8c1226e9b2cd775315c77389ac8f930591019cba8b7c9188b
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: HikariDbPool
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/

bot:
  client:
    username: find_guide_bot
    token: 5957262303:AAEbQPnIvl6EGoOXswWn8xP1Dhvz8PirX-E
  guide:
    username: GuideHelperUzBot
    token: 6000035744:AAEP0RtU5sV_6Xa76-SnPOPrF5EHQXvcE60
  admin:
    username: FindGuideAdminBot
    token: 6205040015:AAGDE1_8UpX46rVhml2_zZr34RRFMQ7a12o
