server:
  port: 8285

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

bot:
  username: find_guide_bot
  token: 5957262303:AAEbQPnIvl6EGoOXswWn8xP1Dhvz8PirX-E
